import 'package:flutter/cupertino.dart';


class Searchword extends StatefulWidget{


  @override
  State<StatefulWidget> createState() {
    return SearchwordState();
  }
}

class SearchwordState  extends State<Searchword>{

  List<String> keywords = [
    "Food",
    "food",
    "Cat",
    "cat",
    "dog",
    "Dog",
    "groceries",
    "Groceries",
    "Money",
    "money",
    "Password",
    "password",
    "Passwords",
    "passwords",
    "Notes",
    "notes",
    "Facebook",
    "facebook",
    "Email",
    "email",
    "Account",
    "account",
    "Dinner",
    "dinner",
    "lunch",
    "Lunch",
    "Gmail",
    "gmail",
    "Yahoo",
    "yahoo",
    "Transport",
    "transport",
    "Pay",
    "pay",
    "Send",
    "send",
    "call",
    "mom",
    "Mom",
    "Dad",
    "dad",
    "brother",
    "create",
    "Create",
    "change",
    "Change",
    "alternative",
    "contact",
    "Contact",
    "Music",
    "music",
    "Playlist",
    "playlist",
    "documents",
    "Documents",
    "document",
    "Document",
    "pdf",
    "Pdf",
    "Signature",
    "signature",
    "Client",
    "client",
    "clients",
    "Clients",
    "change",
    "Change",
    "clothes",
    "update",
    "Update",
    "updates",
    "Updates",
    "terminate",
    "Terminate",
    "word",
    "powerpoint",
    "excel",
    "access",
    "delete",
    "home",
    "Street",
    "street",
    "Avenue",
    "avenue",
    "ave",
    "Ave",
    "corner",
    "fruit",
    "murder",
    "kill",
    "cook",
    "Iphone",
    "iphone",
    "icloud",
    "subscription",
    "Subscription",
    "cancel",
    "Cancel",
    "Doctor",
    "doctor",
    "Dentist",
    "dentist",
    "Mr",
    "mr",
    "Miss",
    "miss",
    "Mrs",
    "Names",
    "Skype",
    "skype",
    "Android",
    "Microsoft",
    "Amazon",
    "Takealot",
    "takealot",
    "centre",
    "Centre",
    "shopping",
    "Shopping",
    "Road",
    "Rd",
    "book",
    "Books",
    "textbook",
    "Textbook",
    "Navigation",
    "navigation",
    "location",
    "Location",
    "WhatsApp",
    "whatsapp",
    "Telegram",
    "telegram",
    "Signal",
    "signal",
    "messages",
    "Messages",
    "course",
    "Courses",
    "Profile",
    "profile",
  ];

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    throw UnimplementedError();
  }
}

